### ISSUE TITLE
Minor schema error for older version of column orientation in table certificate

### ISSUE THREAD

**Issue by yao9394** [mdjnelson/moodle-mod_certificate#68]
+ php admin/cli/check_database_schema.php

certificate
 * column 'orientation' has default ' ', expected 'NULL' (C)

https://github.com/mdjnelson/moodle-mod_certificate/blob/master/db/upgrade.php#L154

It happens when someone upgrade from version under 2.0

**Comment by mdjnelson** [comment]
Thanks, merged.
